name: API-Test

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: Install Newman and HTMLReporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Dir for results
        run: mkdir -p test-results

      - name: Run Postman Collection
        env:
          COLLECTION_ID: ${{secrets.COLLECTION_ID}}
          POSTMAN_KEY: ${{secrets.POSTMAN_API}}
        run: |
          newman run https://api.postman.com/collections/$COLLECTION_ID?access_key=$POSTMAN_KEY

      - name: Output the results
        uses: actions/upload-artifact@v4
        with:
          name: 'test-artifact'
          path: 'test-results'