name: API-Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Newman and HTMLReporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Dir for results
        run: |
          mkdir -p test-results
          ls -la

      - name: Run Postman Collection
        env:
          COLLECTION_ID: ${{secrets.COLLECTION_ID}}
          POSTMAN_KEY: ${{secrets.POSTMAN_KEY}}
        run: |
          set -e
          newman run "https://api.postman.com/collections/${{secrets.COLLECTION_ID}}?access_key=${{secrets.POSTMAN_KEY}}" \
            --reporter-htmlextra \
            --reporter-htmlextra-export "./test-results/report.html"

      - name: Verify report exists
        run: |
          ls -la test-results/
          
      - name: Upload the results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test-results
          if-no-files-found: error
